version : "3.8"
services:
  frontend:
    restart: always
    container_name: frontend1
    image: opemipo/hng-stage2:frontend
    ports:
     - 3000:3000
    depends_on:
      - api
  api:
    restart: always
    container_name: backend1
    image: opemipo/hng-stage2:backend
    ports:
      - 8000:8000